### ISSUE TITLE
Strip traling spaces of values

### ISSUE THREAD

**Issue by 4x0v7** [4x0v7/mdac#2]
Regex `^.+(\s")$`

kickIt track 12 example:

```yaml
---
trackFX:
  name: "Ghz Midside 3 (Goodhertz)"
  type: VST3
  enabled: false
  chainPosition: 4
  parameters:
    advancedPanLink: "Off "
    advancedTiltLink: "On "
    bypass: "bypassed"
    delta: "normal"
    flipLR: "Left | Right "
    inputMode: "Left | Right "
    masterOnOff: "On "
    midGain: "0.5dB"
    midMute: "MUTE "
    midPan: "0%"
    midSolo: "SOLO "
    midTiltGain: "0.0dB"
    midTiltLoudnessMode: "Treble "
    midTiltRangeHigh: "20.0 kHz"
    midTiltRangeLow: "250Hz"
    monoBelowBassMakeup: "0%"
    monoBelowFreq: "Off "
    monoBelowListen: "Off "
    monoBelowStrength: "100%"
    outputMode: "Left | Right "
    sideGain: "2.0dB"
    sideMute: "MUTE "
    sidePan: "0%"
    sideSolo: "SOLO "
    sideTiltGain: "0.0dB"
    sideTiltLoudnessMode: "Treble "
    sideTiltRangeHigh: "20.0 kHz"
    sideTiltRangeLow: "250Hz"
    stereoWidth: "127%"
    stereoWidthMode: "Standard "
    wet: "100"
```
