### ISSUE TITLE
expand yaml schema

### ISSUE THREAD

**Issue by 4x0v7** [4x0v7/mdac#4]
current:
```yaml
--- 
 trackFX: 
   name: "Volume Adjustment" 
   type: JS 
   enabled: true 
   chainPosition: 1 
   parameters: 
     adjustmentDB: "12.0" 
     bypass: "normal" 
     delta: "normal" 
     maxVolumeDB: "0.0" 
     wet: "100"
```

Additions:
```yaml
--- 
 trackName: "Kick"
 trackNumber: 1
 automations:
   - name: lfo01
     speed: "9.7Hz"
     paramRef: trackFX[?name="Volume Adjustment"].parameters.wet
     enabled: true
 trackFX: 
   name: "Volume Adjustment" 
   type: JS 
   enabled: true 
   chainPosition: 1 
   parameters: 
     adjustmentDB: "12.0" 
     bypass: "normal" 
     delta: "normal" 
     maxVolumeDB: "0.0" 
     wet: "100" #-- .automations.[?name="lfo1"]
```

**Comment by 4x0v7** [comment]
gpt says:
```yaml
--- 
 trackName: "Kick"
 trackNumber: 1
 automations:
   - name: lfo01
     speed: "9.7Hz"
     paramRef: "$.trackFX[?(@.name=='Volume Adjustment')].parameters.wet"
     enabled: true
 trackFX: 
   name: "Volume Adjustment" 
   type: JS 
   enabled: true 
   chainPosition: 1 
   parameters: 
     adjustmentDB: "12.0" 
     bypass: "normal" 
     delta: "normal" 
     maxVolumeDB: "0.0" 
     wet: "100" #-- $.automations[?(@.name=='lfo1')]

```
